# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/everywherdo/Software_Engeneering/cse-tichu-example-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/everywherdo/Software_Engeneering/cse-tichu-example-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/everywherdo/Software_Engeneering/cse-tichu-example-project/CMakeFiles /home/everywherdo/Software_Engeneering/cse-tichu-example-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/everywherdo/Software_Engeneering/cse-tichu-example-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tichu-client

# Build rule for target.
Tichu-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tichu-client
.PHONY : Tichu-client

# fast build rule for target.
Tichu-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/build
.PHONY : Tichu-client/fast

#=============================================================================
# Target rules for targets named Tichu-server

# Build rule for target.
Tichu-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tichu-server
.PHONY : Tichu-server

# fast build rule for target.
Tichu-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/build
.PHONY : Tichu-server/fast

#=============================================================================
# Target rules for targets named Tichu-lib

# Build rule for target.
Tichu-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tichu-lib
.PHONY : Tichu-lib

# fast build rule for target.
Tichu-lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/build
.PHONY : Tichu-lib/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/lib/googlemock/CMakeFiles/gmock.dir/build.make googletest/lib/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/lib/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/lib/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/lib/googletest/CMakeFiles/gtest.dir/build.make googletest/lib/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/lib/googletest/CMakeFiles/gtest_main.dir/build.make googletest/lib/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named Tichu-tests

# Build rule for target.
Tichu-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tichu-tests
.PHONY : Tichu-tests

# fast build rule for target.
Tichu-tests/fast:
	$(MAKE) $(MAKESILENT) -f unit-tests/CMakeFiles/Tichu-tests.dir/build.make unit-tests/CMakeFiles/Tichu-tests.dir/build
.PHONY : Tichu-tests/fast

src/client/GameController.o: src/client/GameController.cpp.o
.PHONY : src/client/GameController.o

# target to build an object file
src/client/GameController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/GameController.cpp.o
.PHONY : src/client/GameController.cpp.o

src/client/GameController.i: src/client/GameController.cpp.i
.PHONY : src/client/GameController.i

# target to preprocess a source file
src/client/GameController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/GameController.cpp.i
.PHONY : src/client/GameController.cpp.i

src/client/GameController.s: src/client/GameController.cpp.s
.PHONY : src/client/GameController.s

# target to generate assembly for a file
src/client/GameController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/GameController.cpp.s
.PHONY : src/client/GameController.cpp.s

src/client/app/Tichu.o: src/client/app/Tichu.cpp.o
.PHONY : src/client/app/Tichu.o

# target to build an object file
src/client/app/Tichu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/app/Tichu.cpp.o
.PHONY : src/client/app/Tichu.cpp.o

src/client/app/Tichu.i: src/client/app/Tichu.cpp.i
.PHONY : src/client/app/Tichu.i

# target to preprocess a source file
src/client/app/Tichu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/app/Tichu.cpp.i
.PHONY : src/client/app/Tichu.cpp.i

src/client/app/Tichu.s: src/client/app/Tichu.cpp.s
.PHONY : src/client/app/Tichu.s

# target to generate assembly for a file
src/client/app/Tichu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/app/Tichu.cpp.s
.PHONY : src/client/app/Tichu.cpp.s

src/client/main.o: src/client/main.cpp.o
.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/client/network/ClientNetworkManager.o: src/client/network/ClientNetworkManager.cpp.o
.PHONY : src/client/network/ClientNetworkManager.o

# target to build an object file
src/client/network/ClientNetworkManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/network/ClientNetworkManager.cpp.o
.PHONY : src/client/network/ClientNetworkManager.cpp.o

src/client/network/ClientNetworkManager.i: src/client/network/ClientNetworkManager.cpp.i
.PHONY : src/client/network/ClientNetworkManager.i

# target to preprocess a source file
src/client/network/ClientNetworkManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/network/ClientNetworkManager.cpp.i
.PHONY : src/client/network/ClientNetworkManager.cpp.i

src/client/network/ClientNetworkManager.s: src/client/network/ClientNetworkManager.cpp.s
.PHONY : src/client/network/ClientNetworkManager.s

# target to generate assembly for a file
src/client/network/ClientNetworkManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/network/ClientNetworkManager.cpp.s
.PHONY : src/client/network/ClientNetworkManager.cpp.s

src/client/network/ResponseListenerThread.o: src/client/network/ResponseListenerThread.cpp.o
.PHONY : src/client/network/ResponseListenerThread.o

# target to build an object file
src/client/network/ResponseListenerThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/network/ResponseListenerThread.cpp.o
.PHONY : src/client/network/ResponseListenerThread.cpp.o

src/client/network/ResponseListenerThread.i: src/client/network/ResponseListenerThread.cpp.i
.PHONY : src/client/network/ResponseListenerThread.i

# target to preprocess a source file
src/client/network/ResponseListenerThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/network/ResponseListenerThread.cpp.i
.PHONY : src/client/network/ResponseListenerThread.cpp.i

src/client/network/ResponseListenerThread.s: src/client/network/ResponseListenerThread.cpp.s
.PHONY : src/client/network/ResponseListenerThread.s

# target to generate assembly for a file
src/client/network/ResponseListenerThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/network/ResponseListenerThread.cpp.s
.PHONY : src/client/network/ResponseListenerThread.cpp.s

src/client/panels/ConnectionPanel.o: src/client/panels/ConnectionPanel.cpp.o
.PHONY : src/client/panels/ConnectionPanel.o

# target to build an object file
src/client/panels/ConnectionPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/panels/ConnectionPanel.cpp.o
.PHONY : src/client/panels/ConnectionPanel.cpp.o

src/client/panels/ConnectionPanel.i: src/client/panels/ConnectionPanel.cpp.i
.PHONY : src/client/panels/ConnectionPanel.i

# target to preprocess a source file
src/client/panels/ConnectionPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/panels/ConnectionPanel.cpp.i
.PHONY : src/client/panels/ConnectionPanel.cpp.i

src/client/panels/ConnectionPanel.s: src/client/panels/ConnectionPanel.cpp.s
.PHONY : src/client/panels/ConnectionPanel.s

# target to generate assembly for a file
src/client/panels/ConnectionPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/panels/ConnectionPanel.cpp.s
.PHONY : src/client/panels/ConnectionPanel.cpp.s

src/client/panels/MainGamePanel.o: src/client/panels/MainGamePanel.cpp.o
.PHONY : src/client/panels/MainGamePanel.o

# target to build an object file
src/client/panels/MainGamePanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/panels/MainGamePanel.cpp.o
.PHONY : src/client/panels/MainGamePanel.cpp.o

src/client/panels/MainGamePanel.i: src/client/panels/MainGamePanel.cpp.i
.PHONY : src/client/panels/MainGamePanel.i

# target to preprocess a source file
src/client/panels/MainGamePanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/panels/MainGamePanel.cpp.i
.PHONY : src/client/panels/MainGamePanel.cpp.i

src/client/panels/MainGamePanel.s: src/client/panels/MainGamePanel.cpp.s
.PHONY : src/client/panels/MainGamePanel.s

# target to generate assembly for a file
src/client/panels/MainGamePanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/panels/MainGamePanel.cpp.s
.PHONY : src/client/panels/MainGamePanel.cpp.s

src/client/uiElements/ImagePanel.o: src/client/uiElements/ImagePanel.cpp.o
.PHONY : src/client/uiElements/ImagePanel.o

# target to build an object file
src/client/uiElements/ImagePanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/uiElements/ImagePanel.cpp.o
.PHONY : src/client/uiElements/ImagePanel.cpp.o

src/client/uiElements/ImagePanel.i: src/client/uiElements/ImagePanel.cpp.i
.PHONY : src/client/uiElements/ImagePanel.i

# target to preprocess a source file
src/client/uiElements/ImagePanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/uiElements/ImagePanel.cpp.i
.PHONY : src/client/uiElements/ImagePanel.cpp.i

src/client/uiElements/ImagePanel.s: src/client/uiElements/ImagePanel.cpp.s
.PHONY : src/client/uiElements/ImagePanel.s

# target to generate assembly for a file
src/client/uiElements/ImagePanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/uiElements/ImagePanel.cpp.s
.PHONY : src/client/uiElements/ImagePanel.cpp.s

src/client/uiElements/InputField.o: src/client/uiElements/InputField.cpp.o
.PHONY : src/client/uiElements/InputField.o

# target to build an object file
src/client/uiElements/InputField.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/uiElements/InputField.cpp.o
.PHONY : src/client/uiElements/InputField.cpp.o

src/client/uiElements/InputField.i: src/client/uiElements/InputField.cpp.i
.PHONY : src/client/uiElements/InputField.i

# target to preprocess a source file
src/client/uiElements/InputField.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/uiElements/InputField.cpp.i
.PHONY : src/client/uiElements/InputField.cpp.i

src/client/uiElements/InputField.s: src/client/uiElements/InputField.cpp.s
.PHONY : src/client/uiElements/InputField.s

# target to generate assembly for a file
src/client/uiElements/InputField.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/uiElements/InputField.cpp.s
.PHONY : src/client/uiElements/InputField.cpp.s

src/client/windows/GameWindow.o: src/client/windows/GameWindow.cpp.o
.PHONY : src/client/windows/GameWindow.o

# target to build an object file
src/client/windows/GameWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/windows/GameWindow.cpp.o
.PHONY : src/client/windows/GameWindow.cpp.o

src/client/windows/GameWindow.i: src/client/windows/GameWindow.cpp.i
.PHONY : src/client/windows/GameWindow.i

# target to preprocess a source file
src/client/windows/GameWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/windows/GameWindow.cpp.i
.PHONY : src/client/windows/GameWindow.cpp.i

src/client/windows/GameWindow.s: src/client/windows/GameWindow.cpp.s
.PHONY : src/client/windows/GameWindow.s

# target to generate assembly for a file
src/client/windows/GameWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/client/windows/GameWindow.cpp.s
.PHONY : src/client/windows/GameWindow.cpp.s

src/common/game_state/cards/card.o: src/common/game_state/cards/card.cpp.o
.PHONY : src/common/game_state/cards/card.o

# target to build an object file
src/common/game_state/cards/card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/card.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/card.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/card.cpp.o
.PHONY : src/common/game_state/cards/card.cpp.o

src/common/game_state/cards/card.i: src/common/game_state/cards/card.cpp.i
.PHONY : src/common/game_state/cards/card.i

# target to preprocess a source file
src/common/game_state/cards/card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/card.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/card.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/card.cpp.i
.PHONY : src/common/game_state/cards/card.cpp.i

src/common/game_state/cards/card.s: src/common/game_state/cards/card.cpp.s
.PHONY : src/common/game_state/cards/card.s

# target to generate assembly for a file
src/common/game_state/cards/card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/card.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/card.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/card.cpp.s
.PHONY : src/common/game_state/cards/card.cpp.s

src/common/game_state/cards/discard_pile.o: src/common/game_state/cards/discard_pile.cpp.o
.PHONY : src/common/game_state/cards/discard_pile.o

# target to build an object file
src/common/game_state/cards/discard_pile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/discard_pile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/discard_pile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/discard_pile.cpp.o
.PHONY : src/common/game_state/cards/discard_pile.cpp.o

src/common/game_state/cards/discard_pile.i: src/common/game_state/cards/discard_pile.cpp.i
.PHONY : src/common/game_state/cards/discard_pile.i

# target to preprocess a source file
src/common/game_state/cards/discard_pile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/discard_pile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/discard_pile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/discard_pile.cpp.i
.PHONY : src/common/game_state/cards/discard_pile.cpp.i

src/common/game_state/cards/discard_pile.s: src/common/game_state/cards/discard_pile.cpp.s
.PHONY : src/common/game_state/cards/discard_pile.s

# target to generate assembly for a file
src/common/game_state/cards/discard_pile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/discard_pile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/discard_pile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/discard_pile.cpp.s
.PHONY : src/common/game_state/cards/discard_pile.cpp.s

src/common/game_state/cards/draw_pile.o: src/common/game_state/cards/draw_pile.cpp.o
.PHONY : src/common/game_state/cards/draw_pile.o

# target to build an object file
src/common/game_state/cards/draw_pile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/draw_pile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/draw_pile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/draw_pile.cpp.o
.PHONY : src/common/game_state/cards/draw_pile.cpp.o

src/common/game_state/cards/draw_pile.i: src/common/game_state/cards/draw_pile.cpp.i
.PHONY : src/common/game_state/cards/draw_pile.i

# target to preprocess a source file
src/common/game_state/cards/draw_pile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/draw_pile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/draw_pile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/draw_pile.cpp.i
.PHONY : src/common/game_state/cards/draw_pile.cpp.i

src/common/game_state/cards/draw_pile.s: src/common/game_state/cards/draw_pile.cpp.s
.PHONY : src/common/game_state/cards/draw_pile.s

# target to generate assembly for a file
src/common/game_state/cards/draw_pile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/cards/draw_pile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/cards/draw_pile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/cards/draw_pile.cpp.s
.PHONY : src/common/game_state/cards/draw_pile.cpp.s

src/common/game_state/game_state.o: src/common/game_state/game_state.cpp.o
.PHONY : src/common/game_state/game_state.o

# target to build an object file
src/common/game_state/game_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/game_state.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/game_state.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/game_state.cpp.o
.PHONY : src/common/game_state/game_state.cpp.o

src/common/game_state/game_state.i: src/common/game_state/game_state.cpp.i
.PHONY : src/common/game_state/game_state.i

# target to preprocess a source file
src/common/game_state/game_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/game_state.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/game_state.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/game_state.cpp.i
.PHONY : src/common/game_state/game_state.cpp.i

src/common/game_state/game_state.s: src/common/game_state/game_state.cpp.s
.PHONY : src/common/game_state/game_state.s

# target to generate assembly for a file
src/common/game_state/game_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/game_state.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/game_state.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/game_state.cpp.s
.PHONY : src/common/game_state/game_state.cpp.s

src/common/game_state/player/hand.o: src/common/game_state/player/hand.cpp.o
.PHONY : src/common/game_state/player/hand.o

# target to build an object file
src/common/game_state/player/hand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/player/hand.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/player/hand.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/player/hand.cpp.o
.PHONY : src/common/game_state/player/hand.cpp.o

src/common/game_state/player/hand.i: src/common/game_state/player/hand.cpp.i
.PHONY : src/common/game_state/player/hand.i

# target to preprocess a source file
src/common/game_state/player/hand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/player/hand.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/player/hand.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/player/hand.cpp.i
.PHONY : src/common/game_state/player/hand.cpp.i

src/common/game_state/player/hand.s: src/common/game_state/player/hand.cpp.s
.PHONY : src/common/game_state/player/hand.s

# target to generate assembly for a file
src/common/game_state/player/hand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/player/hand.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/player/hand.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/player/hand.cpp.s
.PHONY : src/common/game_state/player/hand.cpp.s

src/common/game_state/player/player.o: src/common/game_state/player/player.cpp.o
.PHONY : src/common/game_state/player/player.o

# target to build an object file
src/common/game_state/player/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/player/player.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/player/player.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/player/player.cpp.o
.PHONY : src/common/game_state/player/player.cpp.o

src/common/game_state/player/player.i: src/common/game_state/player/player.cpp.i
.PHONY : src/common/game_state/player/player.i

# target to preprocess a source file
src/common/game_state/player/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/player/player.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/player/player.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/player/player.cpp.i
.PHONY : src/common/game_state/player/player.cpp.i

src/common/game_state/player/player.s: src/common/game_state/player/player.cpp.s
.PHONY : src/common/game_state/player/player.s

# target to generate assembly for a file
src/common/game_state/player/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/game_state/player/player.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/game_state/player/player.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/game_state/player/player.cpp.s
.PHONY : src/common/game_state/player/player.cpp.s

src/common/network/requests/client_request.o: src/common/network/requests/client_request.cpp.o
.PHONY : src/common/network/requests/client_request.o

# target to build an object file
src/common/network/requests/client_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/client_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/client_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/client_request.cpp.o
.PHONY : src/common/network/requests/client_request.cpp.o

src/common/network/requests/client_request.i: src/common/network/requests/client_request.cpp.i
.PHONY : src/common/network/requests/client_request.i

# target to preprocess a source file
src/common/network/requests/client_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/client_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/client_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/client_request.cpp.i
.PHONY : src/common/network/requests/client_request.cpp.i

src/common/network/requests/client_request.s: src/common/network/requests/client_request.cpp.s
.PHONY : src/common/network/requests/client_request.s

# target to generate assembly for a file
src/common/network/requests/client_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/client_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/client_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/client_request.cpp.s
.PHONY : src/common/network/requests/client_request.cpp.s

src/common/network/requests/draw_card_request.o: src/common/network/requests/draw_card_request.cpp.o
.PHONY : src/common/network/requests/draw_card_request.o

# target to build an object file
src/common/network/requests/draw_card_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/draw_card_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/draw_card_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/draw_card_request.cpp.o
.PHONY : src/common/network/requests/draw_card_request.cpp.o

src/common/network/requests/draw_card_request.i: src/common/network/requests/draw_card_request.cpp.i
.PHONY : src/common/network/requests/draw_card_request.i

# target to preprocess a source file
src/common/network/requests/draw_card_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/draw_card_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/draw_card_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/draw_card_request.cpp.i
.PHONY : src/common/network/requests/draw_card_request.cpp.i

src/common/network/requests/draw_card_request.s: src/common/network/requests/draw_card_request.cpp.s
.PHONY : src/common/network/requests/draw_card_request.s

# target to generate assembly for a file
src/common/network/requests/draw_card_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/draw_card_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/draw_card_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/draw_card_request.cpp.s
.PHONY : src/common/network/requests/draw_card_request.cpp.s

src/common/network/requests/fold_request.o: src/common/network/requests/fold_request.cpp.o
.PHONY : src/common/network/requests/fold_request.o

# target to build an object file
src/common/network/requests/fold_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/fold_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/fold_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/fold_request.cpp.o
.PHONY : src/common/network/requests/fold_request.cpp.o

src/common/network/requests/fold_request.i: src/common/network/requests/fold_request.cpp.i
.PHONY : src/common/network/requests/fold_request.i

# target to preprocess a source file
src/common/network/requests/fold_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/fold_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/fold_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/fold_request.cpp.i
.PHONY : src/common/network/requests/fold_request.cpp.i

src/common/network/requests/fold_request.s: src/common/network/requests/fold_request.cpp.s
.PHONY : src/common/network/requests/fold_request.s

# target to generate assembly for a file
src/common/network/requests/fold_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/fold_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/fold_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/fold_request.cpp.s
.PHONY : src/common/network/requests/fold_request.cpp.s

src/common/network/requests/join_game_request.o: src/common/network/requests/join_game_request.cpp.o
.PHONY : src/common/network/requests/join_game_request.o

# target to build an object file
src/common/network/requests/join_game_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/join_game_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/join_game_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/join_game_request.cpp.o
.PHONY : src/common/network/requests/join_game_request.cpp.o

src/common/network/requests/join_game_request.i: src/common/network/requests/join_game_request.cpp.i
.PHONY : src/common/network/requests/join_game_request.i

# target to preprocess a source file
src/common/network/requests/join_game_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/join_game_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/join_game_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/join_game_request.cpp.i
.PHONY : src/common/network/requests/join_game_request.cpp.i

src/common/network/requests/join_game_request.s: src/common/network/requests/join_game_request.cpp.s
.PHONY : src/common/network/requests/join_game_request.s

# target to generate assembly for a file
src/common/network/requests/join_game_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/join_game_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/join_game_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/join_game_request.cpp.s
.PHONY : src/common/network/requests/join_game_request.cpp.s

src/common/network/requests/play_card_request.o: src/common/network/requests/play_card_request.cpp.o
.PHONY : src/common/network/requests/play_card_request.o

# target to build an object file
src/common/network/requests/play_card_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/play_card_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/play_card_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/play_card_request.cpp.o
.PHONY : src/common/network/requests/play_card_request.cpp.o

src/common/network/requests/play_card_request.i: src/common/network/requests/play_card_request.cpp.i
.PHONY : src/common/network/requests/play_card_request.i

# target to preprocess a source file
src/common/network/requests/play_card_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/play_card_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/play_card_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/play_card_request.cpp.i
.PHONY : src/common/network/requests/play_card_request.cpp.i

src/common/network/requests/play_card_request.s: src/common/network/requests/play_card_request.cpp.s
.PHONY : src/common/network/requests/play_card_request.s

# target to generate assembly for a file
src/common/network/requests/play_card_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/play_card_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/play_card_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/play_card_request.cpp.s
.PHONY : src/common/network/requests/play_card_request.cpp.s

src/common/network/requests/start_game_request.o: src/common/network/requests/start_game_request.cpp.o
.PHONY : src/common/network/requests/start_game_request.o

# target to build an object file
src/common/network/requests/start_game_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/start_game_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/start_game_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/start_game_request.cpp.o
.PHONY : src/common/network/requests/start_game_request.cpp.o

src/common/network/requests/start_game_request.i: src/common/network/requests/start_game_request.cpp.i
.PHONY : src/common/network/requests/start_game_request.i

# target to preprocess a source file
src/common/network/requests/start_game_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/start_game_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/start_game_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/start_game_request.cpp.i
.PHONY : src/common/network/requests/start_game_request.cpp.i

src/common/network/requests/start_game_request.s: src/common/network/requests/start_game_request.cpp.s
.PHONY : src/common/network/requests/start_game_request.s

# target to generate assembly for a file
src/common/network/requests/start_game_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/requests/start_game_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/requests/start_game_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/requests/start_game_request.cpp.s
.PHONY : src/common/network/requests/start_game_request.cpp.s

src/common/network/responses/full_state_response.o: src/common/network/responses/full_state_response.cpp.o
.PHONY : src/common/network/responses/full_state_response.o

# target to build an object file
src/common/network/responses/full_state_response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/full_state_response.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/full_state_response.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/full_state_response.cpp.o
.PHONY : src/common/network/responses/full_state_response.cpp.o

src/common/network/responses/full_state_response.i: src/common/network/responses/full_state_response.cpp.i
.PHONY : src/common/network/responses/full_state_response.i

# target to preprocess a source file
src/common/network/responses/full_state_response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/full_state_response.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/full_state_response.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/full_state_response.cpp.i
.PHONY : src/common/network/responses/full_state_response.cpp.i

src/common/network/responses/full_state_response.s: src/common/network/responses/full_state_response.cpp.s
.PHONY : src/common/network/responses/full_state_response.s

# target to generate assembly for a file
src/common/network/responses/full_state_response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/full_state_response.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/full_state_response.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/full_state_response.cpp.s
.PHONY : src/common/network/responses/full_state_response.cpp.s

src/common/network/responses/request_response.o: src/common/network/responses/request_response.cpp.o
.PHONY : src/common/network/responses/request_response.o

# target to build an object file
src/common/network/responses/request_response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/request_response.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/request_response.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/request_response.cpp.o
.PHONY : src/common/network/responses/request_response.cpp.o

src/common/network/responses/request_response.i: src/common/network/responses/request_response.cpp.i
.PHONY : src/common/network/responses/request_response.i

# target to preprocess a source file
src/common/network/responses/request_response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/request_response.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/request_response.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/request_response.cpp.i
.PHONY : src/common/network/responses/request_response.cpp.i

src/common/network/responses/request_response.s: src/common/network/responses/request_response.cpp.s
.PHONY : src/common/network/responses/request_response.s

# target to generate assembly for a file
src/common/network/responses/request_response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/request_response.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/request_response.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/request_response.cpp.s
.PHONY : src/common/network/responses/request_response.cpp.s

src/common/network/responses/server_response.o: src/common/network/responses/server_response.cpp.o
.PHONY : src/common/network/responses/server_response.o

# target to build an object file
src/common/network/responses/server_response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/server_response.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/server_response.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/server_response.cpp.o
.PHONY : src/common/network/responses/server_response.cpp.o

src/common/network/responses/server_response.i: src/common/network/responses/server_response.cpp.i
.PHONY : src/common/network/responses/server_response.i

# target to preprocess a source file
src/common/network/responses/server_response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/server_response.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/server_response.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/server_response.cpp.i
.PHONY : src/common/network/responses/server_response.cpp.i

src/common/network/responses/server_response.s: src/common/network/responses/server_response.cpp.s
.PHONY : src/common/network/responses/server_response.s

# target to generate assembly for a file
src/common/network/responses/server_response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/network/responses/server_response.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/network/responses/server_response.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/network/responses/server_response.cpp.s
.PHONY : src/common/network/responses/server_response.cpp.s

src/common/serialization/unique_serializable.o: src/common/serialization/unique_serializable.cpp.o
.PHONY : src/common/serialization/unique_serializable.o

# target to build an object file
src/common/serialization/unique_serializable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/serialization/unique_serializable.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/serialization/unique_serializable.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/serialization/unique_serializable.cpp.o
.PHONY : src/common/serialization/unique_serializable.cpp.o

src/common/serialization/unique_serializable.i: src/common/serialization/unique_serializable.cpp.i
.PHONY : src/common/serialization/unique_serializable.i

# target to preprocess a source file
src/common/serialization/unique_serializable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/serialization/unique_serializable.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/serialization/unique_serializable.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/serialization/unique_serializable.cpp.i
.PHONY : src/common/serialization/unique_serializable.cpp.i

src/common/serialization/unique_serializable.s: src/common/serialization/unique_serializable.cpp.s
.PHONY : src/common/serialization/unique_serializable.s

# target to generate assembly for a file
src/common/serialization/unique_serializable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-client.dir/build.make CMakeFiles/Tichu-client.dir/src/common/serialization/unique_serializable.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/common/serialization/unique_serializable.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/common/serialization/unique_serializable.cpp.s
.PHONY : src/common/serialization/unique_serializable.cpp.s

src/server/game_instance.o: src/server/game_instance.cpp.o
.PHONY : src/server/game_instance.o

# target to build an object file
src/server/game_instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/game_instance.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/game_instance.cpp.o
.PHONY : src/server/game_instance.cpp.o

src/server/game_instance.i: src/server/game_instance.cpp.i
.PHONY : src/server/game_instance.i

# target to preprocess a source file
src/server/game_instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/game_instance.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/game_instance.cpp.i
.PHONY : src/server/game_instance.cpp.i

src/server/game_instance.s: src/server/game_instance.cpp.s
.PHONY : src/server/game_instance.s

# target to generate assembly for a file
src/server/game_instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/game_instance.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/game_instance.cpp.s
.PHONY : src/server/game_instance.cpp.s

src/server/game_instance_manager.o: src/server/game_instance_manager.cpp.o
.PHONY : src/server/game_instance_manager.o

# target to build an object file
src/server/game_instance_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/game_instance_manager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/game_instance_manager.cpp.o
.PHONY : src/server/game_instance_manager.cpp.o

src/server/game_instance_manager.i: src/server/game_instance_manager.cpp.i
.PHONY : src/server/game_instance_manager.i

# target to preprocess a source file
src/server/game_instance_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/game_instance_manager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/game_instance_manager.cpp.i
.PHONY : src/server/game_instance_manager.cpp.i

src/server/game_instance_manager.s: src/server/game_instance_manager.cpp.s
.PHONY : src/server/game_instance_manager.s

# target to generate assembly for a file
src/server/game_instance_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/game_instance_manager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/game_instance_manager.cpp.s
.PHONY : src/server/game_instance_manager.cpp.s

src/server/main.o: src/server/main.cpp.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

src/server/player_manager.o: src/server/player_manager.cpp.o
.PHONY : src/server/player_manager.o

# target to build an object file
src/server/player_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/player_manager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/player_manager.cpp.o
.PHONY : src/server/player_manager.cpp.o

src/server/player_manager.i: src/server/player_manager.cpp.i
.PHONY : src/server/player_manager.i

# target to preprocess a source file
src/server/player_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/player_manager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/player_manager.cpp.i
.PHONY : src/server/player_manager.cpp.i

src/server/player_manager.s: src/server/player_manager.cpp.s
.PHONY : src/server/player_manager.s

# target to generate assembly for a file
src/server/player_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/player_manager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/player_manager.cpp.s
.PHONY : src/server/player_manager.cpp.s

src/server/request_handler.o: src/server/request_handler.cpp.o
.PHONY : src/server/request_handler.o

# target to build an object file
src/server/request_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/request_handler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/request_handler.cpp.o
.PHONY : src/server/request_handler.cpp.o

src/server/request_handler.i: src/server/request_handler.cpp.i
.PHONY : src/server/request_handler.i

# target to preprocess a source file
src/server/request_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/request_handler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/request_handler.cpp.i
.PHONY : src/server/request_handler.cpp.i

src/server/request_handler.s: src/server/request_handler.cpp.s
.PHONY : src/server/request_handler.s

# target to generate assembly for a file
src/server/request_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/request_handler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/request_handler.cpp.s
.PHONY : src/server/request_handler.cpp.s

src/server/server_network_manager.o: src/server/server_network_manager.cpp.o
.PHONY : src/server/server_network_manager.o

# target to build an object file
src/server/server_network_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/server_network_manager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/server_network_manager.cpp.o
.PHONY : src/server/server_network_manager.cpp.o

src/server/server_network_manager.i: src/server/server_network_manager.cpp.i
.PHONY : src/server/server_network_manager.i

# target to preprocess a source file
src/server/server_network_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/server_network_manager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/server_network_manager.cpp.i
.PHONY : src/server/server_network_manager.cpp.i

src/server/server_network_manager.s: src/server/server_network_manager.cpp.s
.PHONY : src/server/server_network_manager.s

# target to generate assembly for a file
src/server/server_network_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-server.dir/build.make CMakeFiles/Tichu-server.dir/src/server/server_network_manager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tichu-lib.dir/build.make CMakeFiles/Tichu-lib.dir/src/server/server_network_manager.cpp.s
.PHONY : src/server/server_network_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Tichu-client"
	@echo "... Tichu-lib"
	@echo "... Tichu-server"
	@echo "... Tichu-tests"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/client/GameController.o"
	@echo "... src/client/GameController.i"
	@echo "... src/client/GameController.s"
	@echo "... src/client/app/Tichu.o"
	@echo "... src/client/app/Tichu.i"
	@echo "... src/client/app/Tichu.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/network/ClientNetworkManager.o"
	@echo "... src/client/network/ClientNetworkManager.i"
	@echo "... src/client/network/ClientNetworkManager.s"
	@echo "... src/client/network/ResponseListenerThread.o"
	@echo "... src/client/network/ResponseListenerThread.i"
	@echo "... src/client/network/ResponseListenerThread.s"
	@echo "... src/client/panels/ConnectionPanel.o"
	@echo "... src/client/panels/ConnectionPanel.i"
	@echo "... src/client/panels/ConnectionPanel.s"
	@echo "... src/client/panels/MainGamePanel.o"
	@echo "... src/client/panels/MainGamePanel.i"
	@echo "... src/client/panels/MainGamePanel.s"
	@echo "... src/client/uiElements/ImagePanel.o"
	@echo "... src/client/uiElements/ImagePanel.i"
	@echo "... src/client/uiElements/ImagePanel.s"
	@echo "... src/client/uiElements/InputField.o"
	@echo "... src/client/uiElements/InputField.i"
	@echo "... src/client/uiElements/InputField.s"
	@echo "... src/client/windows/GameWindow.o"
	@echo "... src/client/windows/GameWindow.i"
	@echo "... src/client/windows/GameWindow.s"
	@echo "... src/common/game_state/cards/card.o"
	@echo "... src/common/game_state/cards/card.i"
	@echo "... src/common/game_state/cards/card.s"
	@echo "... src/common/game_state/cards/discard_pile.o"
	@echo "... src/common/game_state/cards/discard_pile.i"
	@echo "... src/common/game_state/cards/discard_pile.s"
	@echo "... src/common/game_state/cards/draw_pile.o"
	@echo "... src/common/game_state/cards/draw_pile.i"
	@echo "... src/common/game_state/cards/draw_pile.s"
	@echo "... src/common/game_state/game_state.o"
	@echo "... src/common/game_state/game_state.i"
	@echo "... src/common/game_state/game_state.s"
	@echo "... src/common/game_state/player/hand.o"
	@echo "... src/common/game_state/player/hand.i"
	@echo "... src/common/game_state/player/hand.s"
	@echo "... src/common/game_state/player/player.o"
	@echo "... src/common/game_state/player/player.i"
	@echo "... src/common/game_state/player/player.s"
	@echo "... src/common/network/requests/client_request.o"
	@echo "... src/common/network/requests/client_request.i"
	@echo "... src/common/network/requests/client_request.s"
	@echo "... src/common/network/requests/draw_card_request.o"
	@echo "... src/common/network/requests/draw_card_request.i"
	@echo "... src/common/network/requests/draw_card_request.s"
	@echo "... src/common/network/requests/fold_request.o"
	@echo "... src/common/network/requests/fold_request.i"
	@echo "... src/common/network/requests/fold_request.s"
	@echo "... src/common/network/requests/join_game_request.o"
	@echo "... src/common/network/requests/join_game_request.i"
	@echo "... src/common/network/requests/join_game_request.s"
	@echo "... src/common/network/requests/play_card_request.o"
	@echo "... src/common/network/requests/play_card_request.i"
	@echo "... src/common/network/requests/play_card_request.s"
	@echo "... src/common/network/requests/start_game_request.o"
	@echo "... src/common/network/requests/start_game_request.i"
	@echo "... src/common/network/requests/start_game_request.s"
	@echo "... src/common/network/responses/full_state_response.o"
	@echo "... src/common/network/responses/full_state_response.i"
	@echo "... src/common/network/responses/full_state_response.s"
	@echo "... src/common/network/responses/request_response.o"
	@echo "... src/common/network/responses/request_response.i"
	@echo "... src/common/network/responses/request_response.s"
	@echo "... src/common/network/responses/server_response.o"
	@echo "... src/common/network/responses/server_response.i"
	@echo "... src/common/network/responses/server_response.s"
	@echo "... src/common/serialization/unique_serializable.o"
	@echo "... src/common/serialization/unique_serializable.i"
	@echo "... src/common/serialization/unique_serializable.s"
	@echo "... src/server/game_instance.o"
	@echo "... src/server/game_instance.i"
	@echo "... src/server/game_instance.s"
	@echo "... src/server/game_instance_manager.o"
	@echo "... src/server/game_instance_manager.i"
	@echo "... src/server/game_instance_manager.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/player_manager.o"
	@echo "... src/server/player_manager.i"
	@echo "... src/server/player_manager.s"
	@echo "... src/server/request_handler.o"
	@echo "... src/server/request_handler.i"
	@echo "... src/server/request_handler.s"
	@echo "... src/server/server_network_manager.o"
	@echo "... src/server/server_network_manager.i"
	@echo "... src/server/server_network_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

